INSERT INTO user(fname, lname, pesel, password) VALUES
	('Adam', 'Nowak', '15101806178','haslo1'),
	('Halina', 'Borkowska', '67050727680','haslo2'),
	('Modest', 'Łukasik', '77123059459','haslo3'),
	('Eligiusz', 'Ostrowski', '75111917479','haslo4'),
	('Ferdynand', 'Adamski', '85031475096','haslo5'),
	('Waleria', 'Sobczak', '84102628908','haslo6'),
	('Serafina', 'Wysocka', '41022775589','haslo7'),
	('Iwan', 'Piotrowski', '43071843295','haslo8'),
	('Jagoda', 'Pawlak', '80051594446','haslo9'),
	('Lew', 'Sawicki', '92122620693','haslo10'),
	('Augustyn', 'Adamczyk', '61042959819','haslo11'),
	('Paweł', 'Kucharski', '85031475096','haslo12'),
	('Paweł', 'Adamski', '63112362695','haslo13'),
	('Stefania', 'Chmielewska', '70072174086','haslo14'),
	('Felicjan', 'Kalinowski', '94123122372','haslo15'),
	('Barbara', 'Rutkowska', '61072706247','haslo16'),
	('Augustyn', 'Ostrowski', '70070270296','haslo17'),
	('Bogumiła', 'Wysocka', '68022818984','haslo18'),
	('Celina', 'Adamska', '50071139785','haslo19'),
	('Jacek', 'Nowak', '79112858816','haslo20'),
	('Piotr', 'Nowicki', '37101994538','haslo21'),
	('Lubomir', 'Adamczyk', '86111171012','haslo22'),
	('Jarogniew', 'Kowalski', '51051191278','haslo23'),
	('Ryszard', 'Czerwinski', '80063053096','haslo24'),
	('Katarzyna', 'Tomaszewska', '96040359828','haslo25'),
	('Honorata', 'Jasińska', '92020543700','haslo26'),
	('Racław', 'Duda', '65013093991','haslo27'),
	('Kuba', 'Rutkowski', '42012944374','haslo28'),
	('Blanka', 'Wiśniewska', '46072052802','haslo29'),
	('Mateusz', 'Wojciechowski', '82082847939','haslo30');


INSERT INTO sphere(name, description) VALUES
	('edukacja','ustawy dotyczące szkolnictwa, szkół wyższych'),
	('zdrowie','ustawy dotyczące służby zdrowia'),
	('kultura','ustawy dotyczące teatrów, muzeów, działalności kulturalnej'),
	('budżet','ustawy dotyczące budżetu państwa'),
	('cyfryzacja','ustawy dotyczące informatyzacji państwa'),
	('finanse','ustawy dotyczące finansów publicznych, instytucji finansowych'),
	('energia','ustawy dotyczące energii, gospodarki złożami kopalin'),
	('infrastuktura i budownictwo','ustawy dotyczące budownictwa, planowania i zagosopodarowania przestrzeni'),
	('obrona narodowa','ustawy dotyczące obrony narodowej, wojska'),
	('zdrowie','ustawy dotyczące służby zdrowia'),
	('zdrowie','ustawy dotyczące służby zdrowia'),
	('polityka społeczna','ustawy dotyczące pracy, rodziny, zabezpieczenia społecznego'),
	('rolnictwo','ustawy dotyczące rolnictwa, rozwoju wsi, rynku rolnego'),
	('rozwój','ustawy dotyczące gospodarki, rozwoju regionalnego'),
	('sport','ustawy dotyczące kultury fizycznej, turystyki'),
	('sprawy wewnętrzne i administracja','ustawy dotyczące administracji publicznej, służb państwowych'),
	('sądownictwo','ustawy dotyczące sądownictwa, prawa'),
	('sprawy zagraniczne','ustawy dotyczące spraw zagranicznych'),
	('środowisko','ustawy dotyczące ochrony środowiska, gospodarki wodnej');


INSERT INTO act(name, description, sphereID) VALUES
	('Ubezpieczenia upraw rolnych','Ustawa o zmianie ustawy o ubezpieczeniach upraw rolnych i zwierząt gospodarskich oraz ustawy o zmianie ustawy o ubezpieczeniach upraw rolnych i zwierząt gospodarskich',13),
	('Prawo pracy','Rozporządzenie zmieniające rozporządzenie w sprawie przekazania niektórym sądom rejonowym rozpoznawania spraw z zakresu prawa pracy lub ubezpieczeń społecznych z obszarów właściwości innych sądów rejonowych',18),
	('Plan nauczania','Rozporządzenie Ministra Edukacji Narodowej z dnia 28 marca 2017 r. w sprawie ramowych planów nauczania dla publicznych szkół',1),
	('Naczelnicy urzędów celno-skarbowych','Rozporządzenie w sprawie wyznaczenia naczelników urzędów celno-skarbowych właściwych w sprawach rejestracji i eksploatacji automatów do gier, urządzeń losujących i urządzeń do gier oraz określenia obszarów ich właściwości miejscowej',14),
	('Automaty w salonach gier','Rozporządzenie w sprawie zasad usytuowania na terenie gmin salonów gier na automatach',6),
	('Przyznawanie pomocy finansowej','Rozporządzenie w sprawie szczegółowych warunków przyznawania pomocy finansowej w ramach poddziałania „Wsparcie korzystania z usług doradczych” objętego Programem Rozwoju Obszarów Wiejskich na lata 2014–2020 oraz warunków i trybu jej wypłaty',13),
	('Dotacje dla szkół','Rozporządzenie w sprawie udzielania dotacji celowej na wyposażenie szkół w podręczniki, materiały edukacyjne i materiały ćwiczeniowe',1),
	('Pomnik historii','Rozporządzenie Prezydenta Rzeczypospolitej Polskiej w sprawie uznania za pomnik historii „Wąchock – zespół opactwa cystersów”',3),
	('Szkoły mistrzostwa sportowego','Rozporządzenie Ministra Edukacji Narodowej w sprawie oddziałów i szkół sportowych oraz oddziałów i szkół mistrzostwa sportowego',1),
	('Doręczanie wojskowych dokumentów','Rozporządzenie Ministra Obrony Narodowej zmieniające rozporządzenie w sprawie doręczania wojskowych dokumentów osobistych i trybu postępowania z tymi dokumentami',9),
	('Ochrona siedlisk','Rozporządzenie Ministra Środowiska w sprawie specjalnego obszaru ochrony siedlisk Żurawce (PLH060029)',19),
	('Ceny endergii elektrycznej','Rozporządzenie w sprawie ceny referencyjnej energii elektrycznej z odnawialnych źródeł energii w 2017 r. oraz okresów obowiązujących wytwórców, którzy wygrali aukcje w 2017 r.',7),
	('Badania techniczne pojazdów','Rozporządzenie w sprawie badań technicznych pojazdów Sił Zbrojnych Rzeczypospolitej Polskiej, Policji i innych pojazdów użytkowanych w sposób szczególny',16);
	
INSERT INTO proxy(ownUserID, sphereID) VALUES
	(1,4),
	(2,4),
	(4,2),
	(15,13),
	(20,19),
	(23,1),
	(18,9);
	
INSERT INTO userSphereProxy(userID, sphereID, proxyID) VALUES
	(5,1,1),
	(8,13,4),
	(10,19,5),
	(16,9,7),
	(21,4,2);
	
INSERT INTO vote(actID, vote, userID,isProxy) VALUES
	(1,1,1,0),
	(1,1,8,1),
	(1,1,4,0),
	(1,1,2,0),
	(1,1,7,0),
	(1,0,12,0),
	(1,1,14,0),
	(1,0,17,0),
	(1,1,18,0),
	(2,1,1,0),
	(2,1,8,0),
	(2,1,4,0),
	(2,1,2,0),
	(2,1,7,0),
	(3,0,12,0),
	(3,1,14,0),
	(3,0,11,0),
	(3,1,16,0),
	(6,1,7,0),
	(6,1,12,0),
	(6,1,14,0),
	(7,0,11,0),
	(7,1,16,0);